version: '3.8'
services:
  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data
    restart: always

  ai-techradar-backend:
    build:
      target: development
    image: ai-techradar-backend-development
    ports:
      - '3001:3001'
    links:
      - 'mongodb:mongodb'
    depends_on:
      mongodb:
        condition: service_started
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    env_file:
      - '.env'
    environment:
      PORT: 3001
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb:27017/
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
